// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtTVRZxZTaxhgo6vfWUvQuqafHKHBl1J8',
    appId: '1:142458299561:web:ac3b3e3eb341fc790c75b8',
    messagingSenderId: '142458299561',
    projectId: 'sos-tap',
    authDomain: 'sos-tap.firebaseapp.com',
    storageBucket: 'sos-tap.firebasestorage.app',
    measurementId: 'G-0H41708BJG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByyikLfsof3ZpjKCO2sQO7wCNUDkFb_Ws',
    appId: '1:142458299561:android:8058147b7c4b14c60c75b8',
    messagingSenderId: '142458299561',
    projectId: 'sos-tap',
    storageBucket: 'sos-tap.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi40c_5XnmBczyBbxYo4Cs7FM1tF4b2ms',
    appId: '1:142458299561:ios:e9a35c32c02de8a60c75b8',
    messagingSenderId: '142458299561',
    projectId: 'sos-tap',
    storageBucket: 'sos-tap.firebasestorage.app',
    iosBundleId: 'com.example.sosTap',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi40c_5XnmBczyBbxYo4Cs7FM1tF4b2ms',
    appId: '1:142458299561:ios:e9a35c32c02de8a60c75b8',
    messagingSenderId: '142458299561',
    projectId: 'sos-tap',
    storageBucket: 'sos-tap.firebasestorage.app',
    iosBundleId: 'com.example.sosTap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtTVRZxZTaxhgo6vfWUvQuqafHKHBl1J8',
    appId: '1:142458299561:web:6a40467aac47086b0c75b8',
    messagingSenderId: '142458299561',
    projectId: 'sos-tap',
    authDomain: 'sos-tap.firebaseapp.com',
    storageBucket: 'sos-tap.firebasestorage.app',
    measurementId: 'G-65ZM7TFTH7',
  );
}
